### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by qkdkralsgh** [StiphyJay/PillarTrack#1]
Hello, first of all thank you for the good research.

Is there any visualization code in Fig. 6 in the paper?

**Comment by StiphyJay** [comment]
> Hello, first of all thank you for the good research.
> 
> Is there any visualization code in Fig. 6 in the paper?


Hi, please refer to our previous work in visualization:  https://github.com/shanjiayao/PTT, PTT: Point-Track-Transformer Module for 3D Single Object Tracking in Point Clouds,IROS 2021.
