### ISSUE TITLE
配置文件

### ISSUE THREAD

**Issue by bobo-liang** [StiphyJay/PillarTrack#2]
您好，很感谢您的工作。在训练时遇到几个问题想咨询：
1、readme 中提到的yaml文件没有找到,cfg_file 参数具体含义是什么呢？
2、假设数据集kitt在当前目录./data下，batch_size = 2,请问使用什么指令启动训练文件呢？
希望得到您的帮助，感谢！

**Comment by 2986084976** [comment]
感谢你对这项工作的关注，kitti数据集上的cfg文件已经更新；bs可以在cfg文件中进行设定，启动训练文件的命令行如下：python train_track.py --cfg_file cfgs/kitti_models/kitti_car.yaml --extra_tag car

**Comment by WesleyXu224** [comment]
> 您好，很感谢您的工作。在训练时遇到几个问题想咨询： 1、readme 中提到的yaml文件没有找到,cfg_file 参数具体含义是什么呢？ 2、假设数据集kitt在当前目录./data下，batch_size = 2,请问使用什么指令启动训练文件呢？ 希望得到您的帮助，感谢！

感谢你对这项工作的关注，kitti数据集上的cfg文件已经更新；bs可以在cfg文件中进行设定，启动训练文件的命令行如下：python train_track.py --cfg_file cfgs/kitti_models/kitti_car.yaml --extra_tag car

**Comment by bobo-liang** [comment]
感谢！

**Comment by bobo-liang** [comment]
> > 您好，很感谢您的工作。在训练时遇到几个问题想咨询： 1、readme 中提到的yaml文件没有找到,cfg_file 参数具体含义是什么呢？ 2、假设数据集kitt在当前目录./data下，batch_size = 2,请问使用什么指令启动训练文件呢？ 希望得到您的帮助，感谢！
> 
> 感谢你对这项工作的关注，kitti数据集上的cfg文件已经更新；bs可以在cfg文件中进行设定，启动训练文件的命令行如下：python train_track.py --cfg_file cfgs/kitti_models/kitti_car.yaml --extra_tag car

感谢回复！期待其余数据集配置文件完善，也希望您有更多的工作发表！
